```yaml
name: Node.js CI

# Gatilhos de disparo do pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Cria uma máquina virtual Linux isolada na nuvem do GitHub

    steps:
    - name: 1. Baixar codigo do repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar o ambiente Node.js (Versao 20)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: 3. Instalar dependencias (Build automatico)
      run: npm install

    - name: 4. Executar os testes automatizados
      run: npm test
